### ISSUE TITLE
kodi-send --action="UpdateLibrary(video)" wird nicht ausgeführt

### ISSUE THREAD

**Issue by cpy82** [wastis/ShellScriptLauncher#1]
Hallo,
vielen Dank für das super Addon. Genau das, was ich gesucht und benötigt habe!

Den Start von ein paar Bash-Scripten habe ich damit schon erfolgreich umgesetzt. Jetzt wollte ich ein oder mehrere kodi-send Befehle hinzufügen. Hast du vielleicht eine Idee, warum dieses überhaupt nicht funktioniert, obwohl es per SSH problemlos funktioniert?

Folgende Varianten habe ich bereits ausprobiert:

UpdateLibrary1:notify,exitcode 0:kodi-send --action="UpdateLibrary(video)"
UpdateLibrary2:notify,exitcode 0:/usr/bin/kodi-send --action="UpdateLibrary(video)"
UpdateLibrary3:notify,exitcode 0:~/.kodi/userdata/addon_data/script.shellscript.launcher/kodisend_updatelibrary.sh

(die kodisend_updatelibrary.sh beinhaltet dabei auch noch mal den Befehl aus UpdateLibrary1)

Alle drei Varianten funktionieren über SSH problemlos:

LibreELEC:~ # kodi-send --action="UpdateLibrary(video)"
Sending: {'type': 'action', 'content': 'UpdateLibrary(video)'}
LibreELEC:~ # /usr/bin/kodi-send --action="UpdateLibrary(video)"
Sending: {'type': 'action', 'content': 'UpdateLibrary(video)'}
LibreELEC:~ # ~/.kodi/userdata/addon_data/script.shellscript.launcher/kodisend_updatelibrary.sh
Sending: {'type': 'action', 'content': 'UpdateLibrary(video)'}

Nach dem Ausführen von UpdateLibrary1, UpdateLibrary2 oder UpdateLibrary3 aus dem ShellScriptLauncher wird die Ausführung bestätigt, exitcode 0 wird zurückgegeben. Es passiert aber nichts, die Library wird nicht wie beim SSH aktualisiert.

Vielen Dank!

**Comment by wastis** [comment]
Sorry für die verspätete Antwort. 

Eine Ursache für das Problem konnte ich nicht finden, aber dafür einen work-arround.

Der Trick ist, den Update erst zu starten, wenn das ShellScriptLauncher - Addon beendet ist. Das erreicht man indem man zuerst ein  Skript erstellt:

~/tmp/delay.sh:
`#!/bin/bash`
`sleep 1`
`kodi-send --action="UpdateLibrary(video)"`

In der Menüdatei vom ShellScriptLauncher fügt man dann folgende Zeile ein
`Update Library::~/tmp/delay.sh &`

Dabei ist das "&" am Ende wichtig, es verhindert, dass der ShellScriptLauncher auf das Ende des Skriptes wartet. 

Damit sollte es funktionieren.

**Comment by cpy82** [comment]
Perfekt! Hat funktioniert! 👍 

Ganz herzlichen Dank!
